server:
  port: 8082

filePath: /mnt/Plogging_server/images/
contextPath: http://localhost:8082

# File Upload Size
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
