
server:
  port: 8082

filePath: /mnt/duckjiduckji
contextPath: http://localhost:8082

log:
  level: info
  config:
    path: /mnt/duckjiduckji/log
    filename: application-service

# File Upload Size
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


