
server:
  port: 8082

filePath: /data_2/duckjiduckji/fileServer/image/content
contextPath: http://118.32.152.106:40000

# File Upload Size
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


